### PR TITLE
Correct instructions for encoder_test-01.  Clarify instructions & console logs.

### PR DESCRIPTION
**Pull request by cottjr**

### CODE REVIEW

**Comment by paradug** [comment]
Carl,
     It looks like the changes you have made are:

1. Switch from A1/B1 to A2/B2. See my comments below about this.
2. Improve the comments. I especially like the definition if CW.
3. Change motor speed.  The comments about how to adjust the motor speed
for ease of counting the revolutions are good.
4. Alter motor direction commands. I like the comments on the alternate
"if" statements to allow a person to switch from one motor to the other by
just changing the commented lines around. This makes their reason for
existence more clear.


I think this comment :
Note that counts are not exact because the encoder tally is polled for
viewing, even though it is or should be relatively accuratly generated with
interrupt driven scheme used by the encoder library which maintains the
tally.
is inaccurate. The main reason for the small count differences is the
inertia of the wheel, which causes the motor to slightly rotate after the
power is shutoff, though the polling also causes some error. BTW,
accurately is misspelled.

The comment about the possibility of the encoder being mounted 180 degrees
off causing motor directional issues is good. I hadn't thought of that
possible screw up. I would suggest that the comment should say to flip the
A/B connection at the motor controller board. This would be more concise.
Of course it could also be fixed in software.

On my robot the right motor uses A1/B1. It is a matter of how you want to
route the wires. I also use interrupts INT4 and INT5 for the right motor,
instead of INT0 and INT1. I use those interrupts for the left motor, again
a wire routing choice. INT0 and INT1 are easier to get to when you are
first starting your build, and since you are only testing one motor, it
doesn't matter which ones you use.

I like the improvements.

How is your motors panning out? Are the encoders working?

Regards,
Doug P.

**Review by paradug — COMMENTED** [review]
I don't see need to change A1/B1 to A2/B2. Could add that motor shield leads could be either A1/B1 or A2/B2, and encoder wires could be either pins 21,20 or 2,3.

Correct spelling of accurately.

Fix reason for slight difference in count (caused mainly by wheel inertia).

**Comment by cottjr** [comment]
Doug,

no worries on the changes - maybe we can dial in changes Tuesday night then
I can make another pull request.

2 of my three motors are wired one way, the 3rd has the encoder mounted
'backwards'.
one of the magnets was pressed too tightly to the encoder board.
a couple of them rotated 13 to 19 times before reaching the desired count.
Of course the first one seemed to work whereas the other two spun but never
reached count.
After a couple hours of scratching my head, and looking at how things
worked, and looking more closely at the motor/encoder assemblies, I noticed
that the first motor was 'odd man out'.
And I noticed that the hall sensors were unequally spaced.

But all were generating clean 3.3v square waves from the start - although
some of them seemed to have a little different relative transitions.

So,

after pulling the one magnet away from interference,
trying to desolder the backwards one (and finding I didn't have the right
technique or gear to pull it off),
and bending the hall sensors as close as possible towards the magnet w/o
interference,
and slowing the max speed down to minimize inertia after-run,
and flipping the software to compensate for polarity,

I'm able to get all three motors turning pretty consistently...

And, I'm working towards a wiring harness standard (connectorizing &
stackable headers) -
So I'm now into the assembly phase.

BUT, I just noticed that I'm missing a part - lost or something.
So I'll have to print another up Tuesday night before I can mount the main
board...

Anyhow - it's a decent little kit ;)

Carl

**Comment by paradug** [comment]
Carl,
   What part are you missing? I have a few of the small pieces still around.
Regards,
Doug P.

**Comment by cottjr** [comment]
I thought I was missing the adapter plate - but then looked closer and found it...

But if you had 2 of those 4-40 nylon screws - I’d like to borrow them Tuesday night and backfill after my amazon order arrives Wednesday...

**Comment by paradug** [comment]
Carl,
Do you mean the 6-32x1.5" nylon screws used to hold the display? If those
are the wrong screws, let me know where the missing screws are used.
Regards,
Doug P.

**Comment by cottjr** [comment]
Doug -

I mean the 4/40 screws that hold uno and mega to their mounting plates.  I have 4 but need 8 to secure them as well as possible..  big bag of them due in from Amazon on Wed, but I’m hoping to get a little jump on things...

Ie these: screws as I’m attached pic

**Comment by paradug** [comment]
Carl,
   I put 4 4-40 nylon screws in my laptop case. Remind me on Tuesday at
RBNO. See you there.

-Doug P.

**Pull request closed without merging**
